#! /bin/bash

set -euxo pipefail

JEKYLL_ENV=production bundle exec jekyll build --destination docs
git add docs
git commit -m "🤖 Generate new website ($ jekyll build)"

TAG=deployed_at_$(date +"%F_%H-%M")

git tag -m '' -a $TAG
git push --follow-tags
